### ISSUE TITLE
failed to parse valid yaml

### ISSUE THREAD

**Issue by yjh0502** [nathanwhit/minimal-yaml#13]
It fails to parse following input

```
foo:
- baz
bar: bax
```

Here's another one
```
value: {x: -0}
```

Both inputs are parsed by reference parser but failed to parse with the crate.

**Comment by nathanwhit** [comment]
Thanks for the report! I haven't gotten around to porting the entire yaml reference test suite yet, but I hope to before too long. This should be fixed now.

**Comment by yjh0502** [comment]
@nathanwhit Thanks!
